/* ScaleShield case-study data — one source of truth for the listing grid
   (case-studies.html) and the detail template (case-study.html?id=...).
   Add a new object here and it appears in both, automatically. */
window.SS_CASES = [
  {
    id:"marco", name:"Marco V.", initials:"MV", vertical:"Nutra", geo:"EU", tier:"Dual Agency", timeframe:"6 months",
    title:"From <span class='grad'>$40k/mo lost to bans</span> to <span class='grad'>$2.1M/mo running smooth</span>",
    blurb:"Solo EU nutra operator stopped losing $40k/mo to disabled accounts and scaled to $2.1M/mo on Dual Agency.",
    stats:[{n:"52×",l:"Spend growth · 6 mo"},{n:"$0",l:"Lost to bans"},{n:"17",l:"Auto-replacements"},{n:"98%",l:"Uptime SLA hit"}],
    problem:"Marco ran EU nutra offers solo from Lisbon, scaling on personal accounts and resold BMs. The funnel worked — 1.8 ROAS on cold traffic. The problem was the infrastructure: every 2–3 days an account got disabled, costing him 2–4 hours and $80–150 to replace, then a fresh warm-up. His campaigns spent more time paused than running.",
    problemA:{l:"Monthly losses · before",n:"$40,200",s:"Wasted spend during downtime + replacement fees"},
    problemB:{l:"Avg time per ban",n:"3.4 hrs",s:"Find → warm up → restart paused campaigns"},
    solution:"Marco joined the Dual Agency tier — two whitelisted agency accounts running in parallel with unlimited replacements. Risk distribution meant if one flagged, the other kept spending while the CRM auto-fired a replacement. First account was live in his Dolphin Anty within 6 minutes of payment.",
    quote:"First time I've had two accounts on the same offer without something breaking in a week. The Telegram alert was almost comical — by the time I checked, the replacement was already live.",
    quoteBy:"— Marco V., Month 1 on ScaleShield",
    resA:{l:"Month 1 ad spend",n:"$41,800",s:"Same as he was losing/mo before"},
    resB:{l:"Month 6 ad spend",n:"$2.1M",s:"Across both accounts, no bans"},
    results:["Zero ban-related downtime — 17 status flips, all auto-replaced in < 8 min","3× more creative angles tested per week","Telegram alerts replaced 3am Ads Manager refreshing","Flat monthly fee replaced the $40k/mo loss curve"],
    lesson:"The offer didn't change. The creatives didn't change. Only the infrastructure underneath did — and that alone took him from $40k/mo in losses to $2.1M/mo in stable spend."
  },
  {
    id:"sarah", name:"Sarah K.", initials:"SK", vertical:"D2C", geo:"US", tier:"Top Agency + Onyx", timeframe:"11 months",
    title:"Scaling Atlas Media Group to <span class='grad'>$9.6M/mo</span> across 4 verticals with <span class='grad'>Onyx BM2500</span>",
    blurb:"D2C founder eliminated single-point-of-failure risk and scaled 4 brands to $9.6M/mo on Onyx + Top Agency.",
    stats:[{n:"$9.6M",l:"Monthly · month 11"},{n:"2,500",l:"Accounts in hub BM"},{n:"187",l:"Auto-replacements"},{n:"4",l:"Verticals launched"}],
    problem:"Atlas was already big — 4 D2C brands, multiple 7-figure months — but the entire pool funneled through one Business Manager. Every account pushed them toward Meta's 5-share cap, and every BM that went down took 30–80 accounts with it. The portfolio was one policy strike from collapse.",
    problemA:{l:"Concentration risk",n:"100% in 1 BM",s:"Single point of failure for all 4 brands"},
    problemB:{l:"Re-share friction",n:"5-cap weekly",s:"Couldn't move accounts without burning new ones"},
    solution:"Sarah added Top Agency for her highest-spend offers, then layered Onyx BM2500 as the hub. Instead of one BM owning everything, the hub held 2,500 accounts sourced from distributed source BMs. One-click share bypassed the re-share cap entirely, letting her team move accounts between BMs in real time.",
    quote:"Onyx is the only reason we could test 12 offers in parallel without the hub BM ever being a single point of failure. Take that away and we'd be capped at maybe $2M/mo.",
    quoteBy:"— Sarah K., Founder, Atlas Media Group",
    resA:{l:"Month 11 ad spend",n:"$9.6M",s:"All 4 brands, 2,500 accounts active"},
    resB:{l:"Auto-replacements",n:"187",s:"All under 10 min · zero interruptions"},
    results:["Zero BM-down events interrupted the portfolio","187 auto-replacements over 11 months, all < 10 min","4 vertical launches with no infrastructure lift","Dedicated AM handles Meta-rep escalations directly"],
    lesson:"Most founders think the moat is creative or product. At scale it's infrastructure — the pool is the moat, and it's what lets Atlas launch a 5th brand next quarter without rebuilding."
  },
  {
    id:"deepak", name:"Deepak R.", initials:"DR", vertical:"Crypto", geo:"MENA", tier:"Agency Unlimited", timeframe:"9 months",
    title:"Running <span class='grad'>$18M YTD</span> across <span class='grad'>11 parallel BMs</span> in crypto",
    blurb:"MENA crypto affiliate moved off unreliable resellers to 11 parallel BMs and $18M YTD on Agency Unlimited.",
    stats:[{n:"$18M",l:"Spend YTD"},{n:"11",l:"BMs in parallel"},{n:"230+",l:"Replacements · Q1"},{n:"47s",l:"Fastest replacement"}],
    problem:"Deepak runs crypto signal and education funnels across MENA — some of the most policy-sensitive verticals on Meta. His infrastructure was patchwork: resellers ghosting during banwaves, 60+ accounts burned a month at $80–200 each, days of downtime.",
    problemA:{l:"Account spend · before",n:"$12,000/mo",s:"60+ accounts from unreliable resellers"},
    problemB:{l:"Lost ad spend",n:"$20,000/mo",s:"Resellers ghosting during banwaves"},
    solution:"Deepak moved to Agency Unlimited. His dedicated AM mapped offers to 11 BMs by risk profile: 4 for crypto signal funnels, 3 for iGaming, 2 for education, 2 for experimentation. Each BM had its own warm-up history and a priority replacement queue with < 2 min operator response.",
    quote:"Other resellers told me crypto was too risky. ScaleShield replaced 230+ accounts last quarter without me lifting a finger. Telegram ping, then 4 minutes later the new account is in my Dolphin ready to scale.",
    quoteBy:"— Deepak R., MENA Crypto Affiliate",
    resA:{l:"Spend YTD",n:"$18M",s:"Net account cost: $35k/mo flat"},
    resB:{l:"Replacements · Q1",n:"230+",s:"Zero manual intervention"},
    results:["Avg replacement time 4m 12s across 230+ events","Best replacement 47s — replaced before the alert","Zero failed replacements","11 BMs / 0 BM-down interruptions"],
    lesson:"For high-risk verticals the per-account economics don't matter — replacement velocity and supplier trust do. Fixed $35k/mo beat the variable $32–55k/mo of the old patchwork."
  },
  {
    id:"lena", name:"Lena M.", initials:"LM", vertical:"E-commerce", geo:"DE", tier:"Top Agency", timeframe:"5 months",
    title:"German dropshipper from <span class='grad'>$0</span> to <span class='grad'>$1.4M/mo</span> without a single dead campaign",
    blurb:"DACH dropshipping operator launched cold and hit $1.4M/mo in 5 months with zero campaign interruptions.",
    stats:[{n:"$1.4M",l:"Monthly · month 5"},{n:"0",l:"Campaigns lost"},{n:"31",l:"Auto-replacements"},{n:"3.1×",l:"Avg ROAS held"}],
    problem:"Lena had a winning home-goods product but kept getting personal accounts disabled the moment she crossed €500/day. Each ban reset her pixel learning and killed momentum right as the algorithm found her buyers.",
    problemA:{l:"Daily cap before ban",n:"€500",s:"Personal accounts flagged on every scale attempt"},
    problemB:{l:"Pixel resets · month",n:"6–8",s:"Learning phase wiped each disable"},
    solution:"She moved onto Top Agency with high-trust accounts and higher daily ceilings. The CRM auto-replaced any flagged account inside minutes, so her pixel and campaign history stayed intact through scale.",
    quote:"The first month I 5×'d my old ceiling and nothing broke. I didn't realize how much money the bans were quietly costing me until they stopped.",
    quoteBy:"— Lena M., DACH e-commerce",
    resA:{l:"Month 1 ad spend",n:"$180k",s:"Past her old ceiling in week one"},
    resB:{l:"Month 5 ad spend",n:"$1.4M",s:"3.1× ROAS held through scale"},
    results:["Higher daily caps unlocked true scaling","31 replacements, zero campaign interruptions","Pixel learning preserved across every swap","One product line scaled to 7 figures/mo"],
    lesson:"Her product was always good enough for 7 figures. The personal-account ceiling was the only thing keeping her at 5."
  },
  {
    id:"tomas", name:"Tomás R.", initials:"TR", vertical:"Sweepstakes", geo:"LATAM", tier:"Dual Agency", timeframe:"7 months",
    title:"Surviving <span class='grad'>3 banwaves</span> in sweeps with <span class='grad'>zero downtime</span>",
    blurb:"LATAM sweepstakes media buyer rode out three Meta banwaves without losing a day of spend.",
    stats:[{n:"3",l:"Banwaves survived"},{n:"$3.2M",l:"Spend · 7 mo"},{n:"44",l:"Auto-replacements"},{n:"0 days",l:"Downtime"}],
    problem:"Sweepstakes is a banwave magnet. Tomás would lose entire clusters of accounts overnight when Meta swept the vertical, and his old supplier took days to restock — by which point the offer had cooled.",
    problemA:{l:"Accounts lost · banwave",n:"8–15",s:"Whole clusters gone overnight"},
    problemB:{l:"Supplier restock time",n:"2–5 days",s:"Offer cold by the time he was live again"},
    solution:"On Dual Agency with distributed sourcing, banwaves stopped being existential. When a sweep hit, the CRM pulled replacements from unaffected source pools and shared them in within minutes — no waiting on a single supplier.",
    quote:"A banwave used to mean a dead week. Now it means a few Telegram pings and I'm still spending by lunch. The distributed sourcing is the whole game in sweeps.",
    quoteBy:"— Tomás R., LATAM sweepstakes",
    resA:{l:"Worst banwave loss",n:"0 days",s:"Replaced from unaffected pools"},
    resB:{l:"Spend · 7 months",n:"$3.2M",s:"Through 3 separate sweeps"},
    results:["3 banwaves, zero days of lost spend","44 replacements pulled from distributed pools","Offers stayed warm through every sweep","No dependence on a single supplier"],
    lesson:"In sweeps, surviving the banwave is the entire business. Distributed sourcing turned a death sentence into a non-event."
  },
  {
    id:"aisha", name:"Aisha K.", initials:"AK", vertical:"Beauty D2C", geo:"UK", tier:"Single → Top Agency", timeframe:"8 months",
    title:"UK beauty brand scaled clean from <span class='grad'>$60k to $920k/mo</span>",
    blurb:"UK skincare founder graduated from one account to a full agency setup and 6×'d monthly spend.",
    stats:[{n:"15×",l:"Spend growth"},{n:"$920k",l:"Monthly · month 8"},{n:"22",l:"Auto-replacements"},{n:"4.2×",l:"Blended ROAS"}],
    problem:"Aisha's clean-beauty brand had product-market fit but lived in fear of the disable. One flagged account would freeze her best-performing campaign for days, and her agency-of-record charged a fortune for slow replacements.",
    problemA:{l:"Replacement cost · old agency",n:"$300+",s:"Per account, 1–3 day turnaround"},
    problemB:{l:"Best campaign frozen",n:"2–4 days",s:"Every disable killed momentum"},
    solution:"She started on a Single Agency account to test, saw the replacement speed first-hand, and upgraded to Top Agency within a month. Unlimited replacements meant her hero campaigns never sat frozen again.",
    quote:"I tested with one account because I'd been burned before. After the first sub-10-minute replacement I upgraded the same week.",
    quoteBy:"— Aisha K., UK beauty D2C",
    resA:{l:"Starting spend",n:"$60k/mo",s:"On a single test account"},
    resB:{l:"Month 8 spend",n:"$920k/mo",s:"4.2× blended ROAS"},
    results:["Single-account test converted to Top Agency in a week","22 replacements, all under 10 minutes","Hero campaigns never froze again","Replacement cost dropped to zero"],
    lesson:"Starting small to prove the infrastructure is smart. Staying small once it's proven is what costs you."
  },
  {
    id:"viktor", name:"Viktor P.", initials:"VP", vertical:"iGaming", geo:"CIS", tier:"Agency Unlimited", timeframe:"10 months",
    title:"14 BMs running iGaming across CIS at <span class='grad'>$11M+ YTD</span>",
    blurb:"CIS iGaming operator distributed risk across 14 BMs and kept casino offers live at scale.",
    stats:[{n:"14",l:"BMs in parallel"},{n:"$11M",l:"Spend YTD"},{n:"310+",l:"Replacements"},{n:"0",l:"Portfolio-down events"}],
    problem:"Casino offers get hit constantly. Viktor's team juggled accounts across messy spreadsheets and Telegram groups, and a single BM going down would take a whole GEO's campaigns offline for a day or more.",
    problemA:{l:"GEO offline · per BM-down",n:"12–36 hrs",s:"Whole regions dark at once"},
    problemB:{l:"Account tracking",n:"Spreadsheets",s:"No live status across the portfolio"},
    solution:"Agency Unlimited gave him 14 dedicated BMs mapped by GEO, all visible in one CRM with live status. Replacements fired automatically and his AM architected the BM split so no single failure could darken a region.",
    quote:"Fourteen BMs in one dashboard with live status. Before this I was running my whole operation off a spreadsheet and prayer.",
    quoteBy:"— Viktor P., CIS iGaming",
    resA:{l:"Spend YTD",n:"$11M",s:"Across 14 GEO-mapped BMs"},
    resB:{l:"Portfolio-down events",n:"0",s:"No region ever went fully dark"},
    results:["14 BMs split by GEO for risk isolation","310+ replacements, fully automated","Live portfolio status replaced spreadsheets","Dedicated AM owns the BM architecture"],
    lesson:"At iGaming scale, the dashboard IS the operation. Visibility plus distribution is what keeps a region from ever going fully dark."
  },
  {
    id:"jordan", name:"Jordan B.", initials:"JB", vertical:"Info products", geo:"US", tier:"Dual Agency", timeframe:"6 months",
    title:"Course creator scaled a webinar funnel to <span class='grad'>$740k/mo</span> after 9 bans",
    blurb:"US info-product seller stopped the disable cycle and scaled a high-ticket webinar funnel past $700k/mo.",
    stats:[{n:"$740k",l:"Monthly · month 6"},{n:"9→0",l:"Bans before / after"},{n:"19",l:"Auto-replacements"},{n:"2.6×",l:"Funnel ROAS"}],
    problem:"Jordan's high-ticket coaching offer kept tripping Meta's reviews — 9 disables in two months. Each one froze his retargeting audiences and tanked webinar registrations right when paid traffic was warm.",
    problemA:{l:"Disables · 2 months",n:"9",s:"Reviews flagged the coaching angle"},
    problemB:{l:"Retargeting frozen",n:"Each ban",s:"Warm audiences locked out mid-launch"},
    solution:"Dual Agency gave him two parallel accounts with higher trust. When one flagged, retargeting kept running on the other while the CRM swapped the first — so warm audiences never went cold mid-launch.",
    quote:"My launches live and die on retargeting. Keeping it alive through a disable is worth ten times what I pay.",
    quoteBy:"— Jordan B., US info products",
    resA:{l:"Before",n:"9 bans",s:"Webinar regs tanking on every flag"},
    resB:{l:"Month 6 spend",n:"$740k",s:"2.6× funnel ROAS, zero bans"},
    results:["Parallel accounts kept retargeting alive","19 replacements with no launch interrupted","Warm audiences never went cold mid-launch","High-ticket angle ran without review chaos"],
    lesson:"For launch-based funnels, continuity is everything. Two accounts in parallel means a disable never costs you the launch."
  },
  {
    id:"mei", name:"Mei L.", initials:"ML", vertical:"Fashion D2C", geo:"SEA", tier:"Onyx BM2500", timeframe:"9 months",
    title:"SEA fashion label hit <span class='grad'>$4.8M/mo</span> on a single Onyx hub",
    blurb:"Southeast-Asian fashion brand consolidated a chaotic account pool into one Onyx hub and scaled to $4.8M/mo.",
    stats:[{n:"$4.8M",l:"Monthly · month 9"},{n:"2,500",l:"Accounts in hub"},{n:"96",l:"Auto-replacements"},{n:"6",l:"Markets live"}],
    problem:"Mei sold across 6 SEA markets, each with its own accounts and BMs, and managing them was chaos. Currency, GEO, and policy differences meant constant manual reshuffling and frequent dead campaigns in smaller markets.",
    problemA:{l:"Markets · separate setups",n:"6",s:"Each its own account/BM mess"},
    problemB:{l:"Manual reshuffles",n:"Weekly",s:"Moving accounts across markets by hand"},
    solution:"Onyx BM2500 gave her one high-trust hub holding 2,500 accounts, with one-click share to whichever market needed capacity. Distributed sourcing meant a hit in one market never starved the others.",
    quote:"Six markets used to mean six headaches. Now it's one hub and a CRM. I move capacity to whatever market is converting that week.",
    quoteBy:"— Mei L., SEA fashion D2C",
    resA:{l:"Before",n:"6 silos",s:"Chaotic per-market account pools"},
    resB:{l:"Month 9 spend",n:"$4.8M",s:"One hub feeding all 6 markets"},
    results:["One Onyx hub replaced 6 separate setups","One-click capacity shift between markets","96 replacements, no market starved","Currency and GEO juggling eliminated"],
    lesson:"Multi-market operations don't need multi-market chaos. One hub plus one-click share turns six headaches into one dashboard."
  },
  {
    id:"carlos", name:"Carlos D.", initials:"CD", vertical:"Dating", geo:"LATAM", tier:"Top Agency", timeframe:"7 months",
    title:"Dating offers from <span class='grad'>constant bans</span> to <span class='grad'>$1.1M/mo</span> stable",
    blurb:"LATAM dating affiliate took a ban-magnet vertical to $1.1M/mo with unlimited replacements.",
    stats:[{n:"$1.1M",l:"Monthly · month 7"},{n:"38",l:"Auto-replacements"},{n:"< 9 min",l:"Avg replacement"},{n:"0",l:"Days lost"}],
    problem:"Dating is one of Meta's most aggressively policed verticals. Carlos couldn't keep an account alive past a few days, and the constant restart meant his scaling never compounded.",
    problemA:{l:"Account lifespan",n:"3–5 days",s:"Dating flags hit fast and hard"},
    problemB:{l:"Scaling",n:"Never compounded",s:"Restarting from zero every few days"},
    solution:"Top Agency's high-trust accounts lasted meaningfully longer, and when they did flag, unlimited replacements landed in under 9 minutes. For the first time his spend curve went up and stayed up.",
    quote:"In dating you assume you'll lose the account. The difference is whether that costs you a week or nine minutes. Nine minutes lets you actually scale.",
    quoteBy:"— Carlos D., LATAM dating",
    resA:{l:"Before",n:"3–5 day accounts",s:"Scaling reset constantly"},
    resB:{l:"Month 7 spend",n:"$1.1M",s:"Curve finally compounded"},
    results:["Higher-trust accounts lasted longer","38 replacements, avg under 9 minutes","Spend curve compounded for the first time","Zero days lost to the disable cycle"],
    lesson:"You can't stop a ban-magnet vertical from getting banned. You can make the ban cost nine minutes instead of a week."
  },
  {
    id:"ahmed", name:"Ahmed S.", initials:"AS", vertical:"Forex / trading", geo:"MENA", tier:"Agency Unlimited", timeframe:"8 months",
    title:"Forex education scaled to <span class='grad'>$6.3M/mo</span> across 9 BMs",
    blurb:"MENA forex-education operator ran a high-scrutiny vertical to $6.3M/mo on Agency Unlimited.",
    stats:[{n:"$6.3M",l:"Monthly · month 8"},{n:"9",l:"BMs in parallel"},{n:"140+",l:"Replacements"},{n:"< 3 min",l:"Priority queue"}],
    problem:"Forex and trading offers face the same scrutiny as crypto. Ahmed's funnels would scale beautifully for a week, then a cluster of accounts would drop and stall the whole operation for days.",
    problemA:{l:"Account cluster drops",n:"Weekly",s:"Whole funnels stalled for days"},
    problemB:{l:"Replacement source",n:"Single supplier",s:"One choke point for the operation"},
    solution:"Agency Unlimited's 9 BMs and priority replacement queue (< 3 min) meant cluster drops were absorbed instantly across distributed sources. His AM tuned the BM split to his exact funnel mix.",
    quote:"Trading offers scare most providers off. ScaleShield just built me 9 BMs and a sub-3-minute queue and let me run.",
    quoteBy:"— Ahmed S., MENA forex education",
    resA:{l:"Before",n:"Weekly stalls",s:"Cluster drops froze the funnel"},
    resB:{l:"Month 8 spend",n:"$6.3M",s:"Across 9 distributed BMs"},
    results:["9 BMs absorb cluster drops instantly","Sub-3-minute priority replacement queue","140+ replacements, no operation-wide stall","BM split tuned to his funnel mix"],
    lesson:"High-scrutiny verticals need depth, not luck. Nine BMs and a fast queue turn a weekly stall into a non-event."
  },
  {
    id:"sophie", name:"Sophie T.", initials:"ST", vertical:"Supplements", geo:"FR", tier:"Top Agency", timeframe:"6 months",
    title:"French nutra brand from <span class='grad'>$90k to $1.6M/mo</span>",
    blurb:"France-based supplement brand scaled 17× while keeping a compliance-sensitive vertical alive.",
    stats:[{n:"17×",l:"Spend growth"},{n:"$1.6M",l:"Monthly · month 6"},{n:"27",l:"Auto-replacements"},{n:"3.4×",l:"ROAS"}],
    problem:"Supplements in the EU draw heavy compliance review. Sophie's accounts were disabled faster than she could warm them, and her in-house team spent more time managing infrastructure than creative.",
    problemA:{l:"Team time on infra",n:"~40%",s:"Managing accounts instead of creative"},
    problemB:{l:"Warm-up vs ban",n:"Losing race",s:"Disabled before accounts matured"},
    solution:"Top Agency's high-trust accounts and instant replacements freed her team to focus on creative. The CRM handled the infrastructure that used to eat 40% of their week.",
    quote:"My team got their week back. We went from babysitting accounts to actually making ads, and the spend followed immediately.",
    quoteBy:"— Sophie T., FR supplements",
    resA:{l:"Starting spend",n:"$90k/mo",s:"Team bottlenecked on infra"},
    resB:{l:"Month 6 spend",n:"$1.6M",s:"Team refocused on creative"},
    results:["Team time on infrastructure dropped to near zero","27 replacements handled automatically","Creative output and spend rose together","Compliance-heavy vertical stayed live"],
    lesson:"Every hour your team spends babysitting accounts is an hour not spent on creative. Outsource the infrastructure and the spend follows."
  },
  {
    id:"raj", name:"Raj P.", initials:"RP", vertical:"Lead-gen", geo:"US", tier:"Dual Agency", timeframe:"5 months",
    title:"Insurance lead-gen scaled to <span class='grad'>$830k/mo</span> with stable CPLs",
    blurb:"US insurance lead-gen operator held CPL steady at scale by ending account churn.",
    stats:[{n:"$830k",l:"Monthly · month 5"},{n:"18",l:"Auto-replacements"},{n:"−22%",l:"CPL vs before"},{n:"0",l:"Days dark"}],
    problem:"Raj's insurance lead-gen ran on tight CPL margins. Every disabled account forced a fresh learning phase that spiked CPL and blew his client SLAs for days at a time.",
    problemA:{l:"CPL spike · per ban",n:"+30–50%",s:"New learning phase each disable"},
    problemB:{l:"Client SLA breaches",n:"Monthly",s:"Downtime broke delivery promises"},
    solution:"Dual Agency kept a second account warm and learning at all times, so a disable meant shifting budget to an already-optimized account instead of starting cold. CPL stayed flat through swaps.",
    quote:"In lead-gen, a CPL spike from a learning reset is the silent killer. Keeping a warm account ready erased it.",
    quoteBy:"— Raj P., US insurance lead-gen",
    resA:{l:"Before",n:"+30–50% CPL",s:"On every account reset"},
    resB:{l:"Month 5",n:"−22% CPL",s:"Flat through swaps, $830k spend"},
    results:["A second account always warm and optimized","18 replacements with no CPL spike","Client SLAs held every month","Margins stabilized at scale"],
    lesson:"For margin-sensitive lead-gen, the hidden cost of a ban is the learning reset. A warm backup account eliminates it."
  },
  {
    id:"nikolai", name:"Nikolai V.", initials:"NV", vertical:"Casino", geo:"EU", tier:"Onyx BM2500", timeframe:"10 months",
    title:"EU casino operator ran <span class='grad'>$7.9M/mo</span> with BM-level recovery",
    blurb:"European casino affiliate leaned on Onyx BM-level recovery to keep a heavily-policed vertical at scale.",
    stats:[{n:"$7.9M",l:"Monthly · month 10"},{n:"2,500",l:"Accounts in hub"},{n:"210+",l:"Replacements"},{n:"2",l:"Full BM recoveries"}],
    problem:"Casino is the deep end. Twice, Nikolai's hub BM itself got hit — not just accounts, the whole BM — which on any other setup would have wiped his entire operation overnight.",
    problemA:{l:"Hub BM hit",n:"2 times",s:"Whole-BM strikes, not just accounts"},
    problemB:{l:"Recovery elsewhere",n:"Total loss",s:"No way to save accounts from a dead BM"},
    solution:"Onyx's BM-level recovery let him transfer all live accounts from a struck hub into a fresh BM without losing campaign history. Twice the operation should have died — twice it kept running.",
    quote:"My hub BM got killed and I was back up in a new one the same day with my accounts intact. That single feature is worth the whole price.",
    quoteBy:"— Nikolai V., EU casino",
    resA:{l:"Before Onyx",n:"Total loss",s:"A dead hub meant game over"},
    resB:{l:"Month 10 spend",n:"$7.9M",s:"Through 2 full BM recoveries"},
    results:["2 hub-BM strikes survived via recovery","Accounts transferred with history intact","210+ account-level replacements","Never went game-over despite whole-BM hits"],
    lesson:"Account-level replacement isn't enough at the deep end. BM-level recovery is what stands between you and a total wipe."
  },
  {
    id:"bianca", name:"Bianca F.", initials:"BF", vertical:"Skincare D2C", geo:"BR", tier:"Top Agency", timeframe:"7 months",
    title:"Brazilian skincare brand scaled to <span class='grad'>$1.3M/mo</span> in BRL",
    blurb:"Brazil-based skincare founder scaled in-market in BRL without the account churn that capped her before.",
    stats:[{n:"$1.3M",l:"Monthly · month 7"},{n:"24",l:"Auto-replacements"},{n:"3.8×",l:"ROAS"},{n:"0",l:"Days dark"}],
    problem:"Bianca scaled a skincare line in Brazil but local accounts were fragile and her previous supplier didn't understand BRL billing or LATAM policy nuance. Disables stalled her constantly.",
    problemA:{l:"Account fragility",n:"High",s:"Local accounts disabled often"},
    problemB:{l:"Supplier fit",n:"Poor",s:"No grasp of BRL billing / LATAM policy"},
    solution:"Top Agency gave her high-trust accounts suited to her market and a CRM that handled billing and replacements cleanly. Her spend finally tracked her demand instead of her account survival rate.",
    quote:"Finally a setup that understands how we operate in Brazil. My spend tracks demand now, not how many accounts survived the week.",
    quoteBy:"— Bianca F., BR skincare D2C",
    resA:{l:"Before",n:"Constant stalls",s:"Fragile local accounts"},
    resB:{l:"Month 7 spend",n:"$1.3M",s:"3.8× ROAS in BRL"},
    results:["High-trust accounts fit for the market","24 replacements, zero days dark","Clean BRL billing in the CRM","Spend finally tracked real demand"],
    lesson:"Scaling in-market means infrastructure that fits the market. The right accounts plus clean local billing unlock demand you already had."
  },
  {
    id:"kenji", name:"Kenji T.", initials:"KT", vertical:"Mobile gaming", geo:"JP", tier:"Agency Unlimited", timeframe:"9 months",
    title:"Japanese app studio drove <span class='grad'>$5.5M/mo</span> in installs across 8 BMs",
    blurb:"Tokyo mobile-game studio scaled user acquisition across 8 BMs with zero acquisition downtime.",
    stats:[{n:"$5.5M",l:"Monthly · month 9"},{n:"8",l:"BMs in parallel"},{n:"120+",l:"Replacements"},{n:"0",l:"UA-down days"}],
    problem:"Kenji's studio ran aggressive install campaigns for multiple titles. A disabled account meant a title's user-acquisition went dark — and in mobile gaming, a day of dark UA means competitors take your launch window.",
    problemA:{l:"UA dark · per ban",n:"6–24 hrs",s:"A title's installs stopped cold"},
    problemB:{l:"Launch windows",n:"Lost",s:"Competitors filled the gap"},
    solution:"Agency Unlimited dedicated a BM per title with automatic replacements, so no single disable could darken a launch. His AM structured the BMs around his release calendar.",
    quote:"In mobile UA, a dark day during a launch is a dead launch. Eight BMs and instant replacements mean my launches never go dark.",
    quoteBy:"— Kenji T., JP mobile gaming",
    resA:{l:"Before",n:"Lost launches",s:"Dark UA during release windows"},
    resB:{l:"Month 9 spend",n:"$5.5M",s:"Across 8 title-mapped BMs"},
    results:["A dedicated BM per title","120+ replacements, zero UA-down days","Launch windows protected","BM structure built around the release calendar"],
    lesson:"For UA-driven businesses, downtime isn't lost spend — it's a lost launch window. Per-title BMs keep every launch live."
  },
  {
    id:"olivia", name:"Olivia W.", initials:"OW", vertical:"Subscription box", geo:"US / CA", tier:"Top Agency", timeframe:"6 months",
    title:"Subscription box scaled to <span class='grad'>$680k/mo</span> with predictable acquisition",
    blurb:"North-American subscription-box brand made new-subscriber acquisition predictable by ending account churn.",
    stats:[{n:"$680k",l:"Monthly · month 6"},{n:"16",l:"Auto-replacements"},{n:"−18%",l:"CAC vs before"},{n:"0",l:"Days dark"}],
    problem:"Olivia's subscription model lived or died on predictable CAC. Account disables spiked her acquisition cost unpredictably and made her LTV:CAC math impossible to forecast for investors.",
    problemA:{l:"CAC volatility",n:"High",s:"Disables spiked acquisition cost"},
    problemB:{l:"Investor forecasting",n:"Unreliable",s:"LTV:CAC math kept breaking"},
    solution:"Top Agency's stable accounts and instant replacements smoothed her acquisition cost. With infrastructure no longer injecting noise, her CAC became forecastable enough to raise on.",
    quote:"My CAC was a random number generator because of the bans. Now it's a line on a chart I can show investors.",
    quoteBy:"— Olivia W., US/CA subscription box",
    resA:{l:"Before",n:"Volatile CAC",s:"Unforecastable acquisition"},
    resB:{l:"Month 6",n:"−18% CAC",s:"$680k spend, predictable"},
    results:["Stable accounts smoothed acquisition cost","16 replacements, zero days dark","CAC became forecastable for investors","LTV:CAC math finally held"],
    lesson:"Subscription economics need predictable CAC. Stable infrastructure turns acquisition cost from a random number into a forecast."
  },
  {
    id:"hassan", name:"Hassan M.", initials:"HM", vertical:"Crypto education", geo:"MENA", tier:"Onyx BM2500", timeframe:"8 months",
    title:"Crypto-education funnel scaled to <span class='grad'>$4.1M/mo</span> on one Onyx hub",
    blurb:"MENA crypto-education operator consolidated into one Onyx hub and scaled a high-risk funnel cleanly.",
    stats:[{n:"$4.1M",l:"Monthly · month 8"},{n:"2,500",l:"Accounts in hub"},{n:"88",l:"Replacements"},{n:"5",l:"GEOs live"}],
    problem:"Hassan ran crypto-education funnels across 5 MENA GEOs. Managing a separate account pool per GEO was unsustainable, and a hit in one region kept knocking out capacity he needed elsewhere.",
    problemA:{l:"Pools · per GEO",n:"5 separate",s:"Unsustainable to manage"},
    problemB:{l:"Cross-GEO drain",n:"Constant",s:"A hit in one region starved others"},
    solution:"Onyx BM2500 unified everything into one high-trust hub of 2,500 accounts with one-click allocation to any GEO. Distributed sourcing meant a regional hit never starved the rest.",
    quote:"One hub, five GEOs, one CRM. I shift capacity to whichever region is hot without touching five different account pools.",
    quoteBy:"— Hassan M., MENA crypto education",
    resA:{l:"Before",n:"5 pools",s:"Per-GEO account chaos"},
    resB:{l:"Month 8 spend",n:"$4.1M",s:"One hub across 5 GEOs"},
    results:["One Onyx hub replaced 5 GEO pools","One-click capacity allocation per GEO","88 replacements, no region starved","High-risk funnel ran clean at scale"],
    lesson:"Multi-GEO high-risk operations need a single deep pool, not five shallow ones. One hub plus distribution beats five silos every time."
  },
  {
    id:"diego", name:"Diego M.", initials:"DM", vertical:"Nutra COD", geo:"LATAM", tier:"Dual Agency", timeframe:"7 months",
    title:"LATAM nutra COD from <span class='grad'>chaos</span> to <span class='grad'>$2.4M/mo</span>",
    blurb:"LATAM cash-on-delivery nutra operator stabilized a volatile vertical and scaled past $2M/mo.",
    stats:[{n:"$2.4M",l:"Monthly · month 7"},{n:"41",l:"Auto-replacements"},{n:"2.9×",l:"ROAS"},{n:"0",l:"Days dark"}],
    problem:"Diego's COD nutra business across LATAM ran on thin margins and high volume. Account disables didn't just stop spend — they stranded inventory and call-center capacity he'd already committed to.",
    problemA:{l:"Stranded commitments",n:"Per ban",s:"Inventory + call-center sat idle"},
    problemB:{l:"Margin",n:"Thin",s:"No room to absorb downtime"},
    solution:"Dual Agency's parallel accounts kept volume flowing so his downstream operations never sat idle. Replacements landed fast enough that his call center always had leads to work.",
    quote:"In COD, a dead account strands my whole downstream. Keeping volume flowing through a disable is what makes the model work.",
    quoteBy:"— Diego M., LATAM nutra COD",
    resA:{l:"Before",n:"Idle ops",s:"Bans stranded inventory + agents"},
    resB:{l:"Month 7 spend",n:"$2.4M",s:"2.9× ROAS, ops always fed"},
    results:["Parallel accounts kept volume flowing","41 replacements, downstream never idle","Call center always had leads","Thin-margin model stayed profitable"],
    lesson:"In COD, ad downtime strands physical operations. Continuous volume isn't a nicety — it's what keeps the whole model solvent."
  },
  {
    id:"emma", name:"Emma R.", initials:"ER", vertical:"Agency / SMMA", geo:"AU", tier:"Agency Unlimited", timeframe:"11 months",
    title:"Australian agency runs <span class='grad'>40+ client accounts</span> at <span class='grad'>$8.2M/mo</span>",
    blurb:"AU agency owner runs her entire client roster's media buying on ScaleShield infrastructure.",
    stats:[{n:"$8.2M",l:"Monthly · all clients"},{n:"40+",l:"Client accounts"},{n:"260+",l:"Replacements"},{n:"0",l:"Clients churned to bans"}],
    problem:"Emma's agency managed paid social for 40+ clients, and account disables were her #1 churn driver — a client's campaigns going dark for days made her look incompetent even when the work was great.",
    problemA:{l:"#1 churn driver",n:"Account bans",s:"Clients left when campaigns went dark"},
    problemB:{l:"Reputation risk",n:"Every disable",s:"Great work undermined by dead accounts"},
    solution:"On Agency Unlimited she runs her whole roster across dedicated BMs with automatic replacements. Clients never see downtime, so the #1 thing that used to make her churn simply stopped happening.",
    quote:"My clients judge me on whether their ads are running. ScaleShield made 'is it live?' a question I never have to worry about again.",
    quoteBy:"— Emma R., AU agency owner",
    resA:{l:"Before",n:"Ban-driven churn",s:"Downtime cost her clients"},
    resB:{l:"Now",n:"$8.2M/mo",s:"40+ clients, zero ban churn"},
    results:["Whole client roster on dedicated BMs","260+ replacements, clients never saw downtime","#1 churn driver eliminated","Agency reputation protected at scale"],
    lesson:"For agencies, client downtime is reputational. When 'is it live?' stops being a question, churn from bans disappears."
  }
];
